spring:
  application:
    name: mu-admin
  profiles:
    active: dev

--- # redis & cache
spring:
  data:
    redis:
      host: 192.144.238.26
      database: 0
      password: 123456
      port: 6379
      timeout: 10s
      repositories:
        enabled: false
  cache:
    type: redis
    redis:
      time-to-live: 1h

--- # datasource
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mu_admin?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
        reset-enable: false
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
          db-type: mysql
        wall:
          config:
            multi-statement-allow: true

mybatis-plus:
  global-config:
    banner: false
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: AUTO
  mapper-locations: classpath:mappers/*/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.lvpb.mu.modules.*.domain.entity


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    path: /v3/api-docs
  default-flat-param-object: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# 系统自定义配置
mu:
  swagger:
    author: lvpb
    email: lv941226@gmail.com
    version: 1.0.0
    title: Mu Admin Api
    description: 基于SpringBoot3 的管理系统模板
  security:
    token-name: Authorization
    token-prefix: 'Bearer '
    token-expire-time: 3600000
  thread:
    core-pool-size: 8
    max-pool-size: 16
    queue-capacity: 20
    keep-alive-second: 60
    thread-name-prefix: 'mu-thread-'
